name: "my hello action"

description: "say hello with github actions"

inputs:
  first-greeting:
    description: "who would you like to greet in the console"
    required: true
    default: "Hubot"
  
  second-greeting:
    description: "another to greet in the console"
    required: true
    default: "Mona"
  
  third-greeting:
    description: "a third greeting"
    required: false

runs:
  using: "node12"
  main: "main.js"